version: "3"

services:
  pygeoapi:
    image: geopython/pygeoapi:latest
    ports:
      - "80:80"
    volumes:
      - ./app:/app
      - ./pygeoapi-config:/pygeoapi/local.config:ro
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:demo.pygeoapi.io,localhost"
      - "traefik.backend=pygeoapi"
      - "traefik.frontend.priority=100"
      - "traefik.docker.network=pygeoapi-network"

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    command:
      [
        "jupyter",
        "notebook",
        "--ip=0.0.0.0",
        "--port=8888",
        "--no-browser",
        "--allow-root",
        "--notebook-dir=/app",
      ]
